[project]
name = "segment-anything-character-extraction"
description = "Manga character extraction using SAM + YOLO"
version = "1.0.0"

[models]
# SAM Model Configuration
sam_model_type = "vit_h"
sam_checkpoint = "sam_vit_h_4b8939.pth"
sam_device = "auto"  # auto, cuda, cpu

# YOLO Model Configuration  
yolo_model_path = "yolov8n.pt"
yolo_confidence_threshold = 0.25

[extraction]
# Image Processing
max_image_size = 1024
min_image_size = 512
enhance_contrast = false

# Mask Filtering
min_mask_area = 1000
max_area_ratio = 0.8
min_aspect_ratio = 0.3
max_aspect_ratio = 3.0

# YOLO Scoring
min_yolo_score = 0.1
yolo_weight = 0.4
sam_weight = 0.6

# Text Detection
filter_text_regions = true
max_text_density = 0.3
text_detection_method = "easyocr"  # easyocr, opencv

# Post-processing
remove_small_components = 100
smooth_kernel_size = 3
fill_holes = true
crop_padding = 10

[output]
# File Formats
save_mask = false
save_transparent = false
output_format = "jpg"
mask_format = "png"

# Background
background_color = [0, 0, 0]  # RGB

[performance]
# Memory Management
enable_garbage_collection = true
clear_gpu_cache = true
monitor_performance = true

# Batch Processing
batch_size = 1
parallel_processing = false

[logging]
level = "INFO"  # DEBUG, INFO, WARNING, ERROR
show_progress = true
save_logs = false

[paths]
# Default Paths
default_output_dir = "character_output"
temp_dir = "temp"
log_dir = "logs"

[advanced]
# SAM Advanced Settings
sam_points_per_side = 32
sam_pred_iou_thresh = 0.8
sam_stability_score_thresh = 0.85
sam_crop_n_layers = 1
sam_min_mask_region_area = 100

# Debug Options
debug_mode = false
save_intermediate_results = false
show_mask_overlay = false