#!/usr/bin/env python3
"""
設定管理統合ツール
Markdownファイルでの変数展開とワークスペース管理を統合
"""

import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional

# プロジェクトルートをパスに追加
sys.path.insert(0, str(Path(__file__).parent.parent))
from config.workspace_config import WorkspaceConfig


class ConfigManager:
    """統合設定管理システム"""

    def __init__(self):
        """初期化"""
        self.workspace_config = WorkspaceConfig()

    def get_all_variables(self) -> Dict[str, str]:
        """
        すべての設定変数を取得

        Returns:
            設定変数辞書
        """
        variables = {}

        # ワークスペース関連
        env_vars = self.workspace_config.export_environment_variables()
        variables.update(env_vars)

        # 追加の重要変数
        variables.update(
            {
                "PROJECT_ROOT": str(Path(__file__).parent.parent),
                "DEFAULT_INPUT_DIR": "/mnt/c/AItools/lora/train/yado/org/kana05",
                "PUSHOVER_CONFIG": str(Path(__file__).parent.parent / "config" / "pushover.json"),
                "SAM_MODEL_PATH": "sam_vit_h_4b8939.pth",
                "YOLO_MODEL_PATH": "yolov8x.pt",
            }
        )

        return variables

    def expand_variables_in_text(self, text: str) -> str:
        """
        テキスト内の変数を展開

        Args:
            text: 展開対象テキスト

        Returns:
            変数展開済みテキスト
        """
        variables = self.get_all_variables()

        # ${VAR_NAME} パターンをサポート
        def replace_var(match):
            var_name = match.group(1)
            return variables.get(var_name, match.group(0))

        # 変数展開
        expanded = re.sub(r"\$\{([^}]+)\}", replace_var, text)

        return expanded

    def update_markdown_file(self, file_path: Path, backup: bool = True) -> bool:
        """
        Markdownファイルの変数を展開して更新

        Args:
            file_path: 更新対象ファイル
            backup: バックアップ作成フラグ

        Returns:
            更新成功フラグ
        """
        try:
            if not file_path.exists():
                return False

            # バックアップ作成
            if backup:
                backup_path = file_path.with_suffix(f"{file_path.suffix}.backup")
                backup_path.write_text(file_path.read_text(), encoding="utf-8")

            # ファイル読み込み
            content = file_path.read_text(encoding="utf-8")

            # 変数展開
            expanded_content = self.expand_variables_in_text(content)

            # 変更があった場合のみ更新
            if content != expanded_content:
                file_path.write_text(expanded_content, encoding="utf-8")
                return True

            return False

        except Exception as e:
            print(f"❌ Error updating {file_path}: {e}")
            return False

    def generate_environment_script(self, shell_type: str = "bash") -> str:
        """
        環境変数設定スクリプトを生成

        Args:
            shell_type: シェル種別 (bash, zsh, fish)

        Returns:
            環境変数設定スクリプト
        """
        variables = self.get_all_variables()

        if shell_type in ["bash", "zsh"]:
            lines = []
            lines.append(f"#!/bin/{shell_type}")
            lines.append("# 自動生成された環境変数設定ファイル")
            lines.append("# Do not edit manually - generated by tools/config_manager.py")
            lines.append("")

            for key, value in variables.items():
                lines.append(f'export {key}="{value}"')

            return "\n".join(lines)

        elif shell_type == "fish":
            lines = []
            lines.append("# 自動生成された環境変数設定ファイル (Fish Shell)")
            lines.append("# Do not edit manually - generated by tools/config_manager.py")
            lines.append("")

            for key, value in variables.items():
                lines.append(f'set -gx {key} "{value}"')

            return "\n".join(lines)

        else:
            raise ValueError(f"Unsupported shell type: {shell_type}")

    def create_markdown_template(self) -> str:
        """
        Markdown変数参照テンプレートを生成

        Returns:
            Markdownテンプレート
        """
        variables = self.get_all_variables()

        lines = []
        lines.append("# 設定変数リファレンス")
        lines.append("")
        lines.append("このドキュメントでは以下の変数が使用可能です：")
        lines.append("")

        for key, value in sorted(variables.items()):
            lines.append(f"- `${{{key}}}` → `{value}`")

        lines.append("")
        lines.append("## 使用例")
        lines.append("")
        lines.append("```bash")
        lines.append("# 抽出コマンド例")
        lines.append("python features/extraction/commands/extract_character.py \\")
        lines.append("  --input_dir ${DEFAULT_INPUT_DIR} \\")
        lines.append("  --output_dir ${TRACKER_WORKSPACE_BASE}/${TRACKER_ID}/extraction/")
        lines.append("```")

        return "\n".join(lines)

    def validate_configuration(self) -> Dict[str, bool]:
        """
        設定の妥当性を検証

        Returns:
            検証結果辞書
        """
        results = {}

        # ワークスペースパス検証
        results["workspace_path_valid"] = self.workspace_config.validate_workspace_path()

        # 必須ディレクトリ存在確認
        variables = self.get_all_variables()
        input_dir = Path(variables.get("DEFAULT_INPUT_DIR", ""))
        results["input_dir_exists"] = input_dir.exists()

        # モデルファイル存在確認
        project_root = Path(variables.get("PROJECT_ROOT", "."))
        sam_model = project_root / variables.get("SAM_MODEL_PATH", "")
        results["sam_model_exists"] = sam_model.exists()

        yolo_model = project_root / variables.get("YOLO_MODEL_PATH", "")
        results["yolo_model_exists"] = yolo_model.exists()

        return results


def main():
    """メイン実行"""
    import argparse

    parser = argparse.ArgumentParser(description="統合設定管理ツール")
    parser.add_argument("--show-vars", action="store_true", help="すべての変数を表示")
    parser.add_argument("--generate-env", choices=["bash", "zsh", "fish"], help="環境変数スクリプト生成")
    parser.add_argument("--update-markdown", type=Path, help="Markdownファイルの変数展開")
    parser.add_argument("--validate", action="store_true", help="設定妥当性検証")
    parser.add_argument("--template", action="store_true", help="Markdownテンプレート生成")

    args = parser.parse_args()

    manager = ConfigManager()

    if args.show_vars:
        print("=== 設定変数一覧 ===")
        variables = manager.get_all_variables()
        for key, value in sorted(variables.items()):
            print(f"{key} = {value}")

    elif args.generate_env:
        script = manager.generate_environment_script(args.generate_env)
        print(script)

    elif args.update_markdown:
        success = manager.update_markdown_file(args.update_markdown)
        if success:
            print(f"✅ Updated: {args.update_markdown}")
        else:
            print(f"❌ No changes: {args.update_markdown}")

    elif args.validate:
        print("=== 設定検証結果 ===")
        results = manager.validate_configuration()
        for key, is_valid in results.items():
            status = "✅" if is_valid else "❌"
            print(f"{status} {key}: {is_valid}")

    elif args.template:
        template = manager.create_markdown_template()
        print(template)

    else:
        # デフォルト：概要表示
        print("=== 統合設定管理システム ===")
        config_summary = WorkspaceConfig.get_config_summary()

        print(f"Workspace Base: {config_summary['workspace_base']}")
        print(f"From Environment: {config_summary['from_environment']}")
        print(f"Path Valid: {config_summary['path_valid']}")
        print("")
        print("利用可能コマンド:")
        print("  --show-vars     : 全変数表示")
        print("  --generate-env  : 環境変数スクリプト生成")
        print("  --update-markdown : Markdown変数展開")
        print("  --validate      : 設定検証")
        print("  --template      : Markdownテンプレート生成")


if __name__ == "__main__":
    main()
