# TEMPORARILY DISABLED - Claude GitHub App not responding
# name: Claude for GitHub

# on:
#   issues:
#     types: [opened, edited]
#   issue_comment:
#     types: [created, edited]
#   pull_request:
#     types: [opened, edited, synchronize]
#   pull_request_review_comment:
#     types: [created, edited]

# permissions:
#   contents: write
#   issues: write
#   pull-requests: write

# jobs:
#   claude:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Claude for GitHub
#         uses: anthropics/claude-code-action@v1
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}