name: Claude

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: anthropics/claude-github-action@v1
      with:
        api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        max-tokens: 4096